--------------------------------------------------------
--  File created - Monday-January-12-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACADEMICSTAFF
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ACADEMICSTAFF" 
   (	"STAFFNO" VARCHAR2(10 BYTE), 
	"FIRSTNAME" VARCHAR2(100 BYTE), 
	"LASTNAME" VARCHAR2(100 BYTE), 
	"PHONEEXTENSION" NUMBER(*,0), 
	"OFFICENO" NUMBER(*,0), 
	"SEX" VARCHAR2(10 BYTE), 
	"STREET" VARCHAR2(100 BYTE), 
	"TOWN" VARCHAR2(100 BYTE), 
	"POSTCODE" VARCHAR2(15 BYTE), 
	"SALARY" NUMBER(8,2), 
	"POST" VARCHAR2(50 BYTE), 
	"QUALIFICATIONS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACADEMICSTAFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ACADEMICSTAFF_PK" ON "SYSTEM"."ACADEMICSTAFF" ("STAFFNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACADEMICSTAFF
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ACADEMICSTAFF" MODIFY ("STAFFNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACADEMICSTAFF" ADD CONSTRAINT "ACADEMICSTAFF_PK" PRIMARY KEY ("STAFFNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
