--------------------------------------------------------
--  File created - Monday-January-12-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACADEMICSTAFFTEACHESMODULE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ACADEMICSTAFFTEACHESMODULE" 
   (	"STAFFNO" VARCHAR2(10 BYTE), 
	"MODULECODE" VARCHAR2(10 BYTE), 
	"HOURSPERWEEK" NUMBER(*,0), 
	"MODULE_MODULECODE" VARCHAR2(10 BYTE), 
	"MODULE_COURSECODE1" VARCHAR2(10 BYTE), 
	"MODULE_DEPTID1" VARCHAR2(10 BYTE), 
	"ACADEMICSTAFF_STAFFNO" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACADEMICSTAFFTEACHESMODULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ACADEMICSTAFFTEACHESMODULE_PK" ON "SYSTEM"."ACADEMICSTAFFTEACHESMODULE" ("STAFFNO", "MODULECODE", "MODULE_MODULECODE", "MODULE_COURSECODE1", "MODULE_DEPTID1", "ACADEMICSTAFF_STAFFNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACADEMICSTAFFTEACHESMODULE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ACADEMICSTAFFTEACHESMODULE" MODIFY ("STAFFNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACADEMICSTAFFTEACHESMODULE" MODIFY ("MODULECODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACADEMICSTAFFTEACHESMODULE" MODIFY ("MODULE_MODULECODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACADEMICSTAFFTEACHESMODULE" MODIFY ("MODULE_COURSECODE1" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACADEMICSTAFFTEACHESMODULE" MODIFY ("MODULE_DEPTID1" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACADEMICSTAFFTEACHESMODULE" MODIFY ("ACADEMICSTAFF_STAFFNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACADEMICSTAFFTEACHESMODULE" ADD CONSTRAINT "ACADEMICSTAFFTEACHESMODULE_PK" PRIMARY KEY ("STAFFNO", "MODULECODE", "MODULE_MODULECODE", "MODULE_COURSECODE1", "MODULE_DEPTID1", "ACADEMICSTAFF_STAFFNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACADEMICSTAFFTEACHESMODULE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ACADEMICSTAFFTEACHESMODULE" ADD CONSTRAINT "ACADEMICSTAFFTEACHESMODULE_ACADEMICSTAFF_FK" FOREIGN KEY ("ACADEMICSTAFF_STAFFNO")
	  REFERENCES "SYSTEM"."ACADEMICSTAFF" ("STAFFNO") ON DELETE CASCADE ENABLE;
