--------------------------------------------------------
--  File created - Monday-January-12-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COURSE" 
   (	"COURSECODE" VARCHAR2(10 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"DURATIONINYEARS" VARCHAR2(2 BYTE), 
	"DEPTID" VARCHAR2(10 BYTE), 
	"LEADERSTAFFNO" VARCHAR2(10 BYTE), 
	"DEPARTMENT_DEPTID" VARCHAR2(10 BYTE), 
	"ACADEMICSTAFF_STAFFNO" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COURSE__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COURSE__IDX" ON "SYSTEM"."COURSE" ("ACADEMICSTAFF_STAFFNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COURSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COURSE_PK" ON "SYSTEM"."COURSE" ("COURSECODE", "DEPARTMENT_DEPTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COURSE" MODIFY ("COURSECODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."COURSE" MODIFY ("DEPARTMENT_DEPTID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."COURSE" MODIFY ("ACADEMICSTAFF_STAFFNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY ("COURSECODE", "DEPARTMENT_DEPTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
