--------------------------------------------------------
--  File created - Monday-January-12-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPARTMENTMANAGER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DEPARTMENTMANAGER" 
   (	"STAFFNO" VARCHAR2(10 BYTE), 
	"DEPTID" VARCHAR2(10 BYTE), 
	"STARTDATE" DATE, 
	"ACADEMICSTAFF_STAFFNO" VARCHAR2(10 BYTE), 
	"DEPARTMENT_DEPTID" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENTMANAGER__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DEPARTMENTMANAGER__IDX" ON "SYSTEM"."DEPARTMENTMANAGER" ("ACADEMICSTAFF_STAFFNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENTMANAGER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DEPARTMENTMANAGER_PK" ON "SYSTEM"."DEPARTMENTMANAGER" ("STAFFNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DEPARTMENTMANAGER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DEPARTMENTMANAGER" MODIFY ("STAFFNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DEPARTMENTMANAGER" MODIFY ("ACADEMICSTAFF_STAFFNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DEPARTMENTMANAGER" MODIFY ("DEPARTMENT_DEPTID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DEPARTMENTMANAGER" ADD CONSTRAINT "DEPARTMENTMANAGER_PK" PRIMARY KEY ("STAFFNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
