--------------------------------------------------------
--  File created - Monday-January-12-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MODULE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MODULE" 
   (	"MODULECODE" VARCHAR2(10 BYTE), 
	"TITLE" VARCHAR2(150 BYTE), 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"EXAMPERCENTAGE" NUMBER(5,2), 
	"COURSEWORKPERCENTAGE" NUMBER(5,2), 
	"COURSECODE" VARCHAR2(10 BYTE), 
	"COORDINATORSTAFFNO" VARCHAR2(10 BYTE), 
	"COURSE_COURSECODE" VARCHAR2(10 BYTE), 
	"COURSE_DEPTID1" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MODULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."MODULE_PK" ON "SYSTEM"."MODULE" ("MODULECODE", "COURSE_COURSECODE", "COURSE_DEPTID1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MODULE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MODULE" MODIFY ("MODULECODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MODULE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MODULE" MODIFY ("COURSECODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MODULE" MODIFY ("COORDINATORSTAFFNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MODULE" MODIFY ("COURSE_COURSECODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MODULE" MODIFY ("COURSE_DEPTID1" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MODULE" ADD CONSTRAINT "MODULE_PK" PRIMARY KEY ("MODULECODE", "COURSE_COURSECODE", "COURSE_DEPTID1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
