--------------------------------------------------------
--  File created - Monday-January-12-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NEXTOFKIN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."NEXTOFKIN" 
   (	"MATRICULATIONNO" VARCHAR2(10 BYTE), 
	"FIRSTNAME" VARCHAR2(100 BYTE), 
	"LASTNAME" VARCHAR2(100 BYTE), 
	"TOWN" VARCHAR2(100 BYTE), 
	"STREET" VARCHAR2(100 BYTE), 
	"POSTCODE" VARCHAR2(15 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"RELATIONSHIP" VARCHAR2(50 BYTE), 
	"STUDENT_MATRICULATIONNO" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NEXTOFKIN__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."NEXTOFKIN__IDX" ON "SYSTEM"."NEXTOFKIN" ("STUDENT_MATRICULATIONNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NEXTOFKIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."NEXTOFKIN_PK" ON "SYSTEM"."NEXTOFKIN" ("MATRICULATIONNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NEXTOFKIN
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NEXTOFKIN" MODIFY ("MATRICULATIONNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NEXTOFKIN" MODIFY ("STUDENT_MATRICULATIONNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NEXTOFKIN" ADD CONSTRAINT "NEXTOFKIN_PK" PRIMARY KEY ("MATRICULATIONNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NEXTOFKIN
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NEXTOFKIN" ADD CONSTRAINT "NEXTOFKIN_STUDENT_FK" FOREIGN KEY ("STUDENT_MATRICULATIONNO")
	  REFERENCES "SYSTEM"."STUDENT" ("MATRICULATIONNO") ON DELETE CASCADE ENABLE;
