--------------------------------------------------------
--  File created - Monday-January-12-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDENTMODULEPERFORMANCE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STUDENTMODULEPERFORMANCE" 
   (	"MATRICULATIONNO" VARCHAR2(10 BYTE), 
	"MODULECODE" VARCHAR2(10 BYTE), 
	"PERFORMANCE" VARCHAR2(20 BYTE), 
	"MODULE_MODULECODE" VARCHAR2(10 BYTE), 
	"MODULE_COURSE_COURSECODE" VARCHAR2(10 BYTE), 
	"MODULE_COURSE_DEPTID1" VARCHAR2(10 BYTE), 
	"STUDENT_MATRICULATIONNO" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENTMODULEPERFORMANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."STUDENTMODULEPERFORMANCE_PK" ON "SYSTEM"."STUDENTMODULEPERFORMANCE" ("MATRICULATIONNO", "MODULECODE", "MODULE_MODULECODE", "MODULE_COURSE_COURSECODE", "MODULE_COURSE_DEPTID1", "STUDENT_MATRICULATIONNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STUDENTMODULEPERFORMANCE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STUDENTMODULEPERFORMANCE" MODIFY ("MATRICULATIONNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTMODULEPERFORMANCE" MODIFY ("MODULECODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTMODULEPERFORMANCE" MODIFY ("MODULE_MODULECODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTMODULEPERFORMANCE" MODIFY ("MODULE_COURSE_COURSECODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTMODULEPERFORMANCE" MODIFY ("MODULE_COURSE_DEPTID1" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTMODULEPERFORMANCE" MODIFY ("STUDENT_MATRICULATIONNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTMODULEPERFORMANCE" ADD CONSTRAINT "STUDENTMODULEPERFORMANCE_PK" PRIMARY KEY ("MATRICULATIONNO", "MODULECODE", "MODULE_MODULECODE", "MODULE_COURSE_COURSECODE", "MODULE_COURSE_DEPTID1", "STUDENT_MATRICULATIONNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENTMODULEPERFORMANCE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STUDENTMODULEPERFORMANCE" ADD CONSTRAINT "STUDENTMODULEPERFORMANCE_STUDENT_FK" FOREIGN KEY ("STUDENT_MATRICULATIONNO")
	  REFERENCES "SYSTEM"."STUDENT" ("MATRICULATIONNO") ON DELETE CASCADE ENABLE;
