--------------------------------------------------------
--  File created - Monday-January-12-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STUDENT" 
   (	"MATRICULATIONNO" VARCHAR2(10 BYTE), 
	"FIRSTNAME" VARCHAR2(100 BYTE), 
	"LASTNAME" VARCHAR2(100 BYTE), 
	"DOB" DATE, 
	"SEX" VARCHAR2(10 BYTE), 
	"FINACIALLOAN" NUMBER(6,2), 
	"TOWN" VARCHAR2(100 BYTE), 
	"STREET" VARCHAR2(100 BYTE), 
	"POSTCODE" VARCHAR2(15 BYTE), 
	"USERID" VARCHAR2(10 BYTE), 
	"COURSECODE" VARCHAR2(10 BYTE), 
	"COURSE_COURSECODE" VARCHAR2(10 BYTE), 
	"COURSE_DEPTID1" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."STUDENT_PK" ON "SYSTEM"."STUDENT" ("MATRICULATIONNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STUDENT" MODIFY ("MATRICULATIONNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENT" MODIFY ("COURSE_COURSECODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENT" MODIFY ("COURSE_DEPTID1" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("MATRICULATIONNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
