--------------------------------------------------------
--  File created - Monday-January-12-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEXTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TEXTS" 
   (	"TEXTID" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(150 BYTE), 
	"MODULECODE" VARCHAR2(10 BYTE), 
	"MODULE_MODULECODE" VARCHAR2(10 BYTE), 
	"MODULE_COURSECODE1" VARCHAR2(10 BYTE), 
	"MODULE_DEPTID1" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TEXTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TEXTS_PK" ON "SYSTEM"."TEXTS" ("TEXTID", "MODULE_MODULECODE", "MODULE_COURSECODE1", "MODULE_DEPTID1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TEXTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TEXTS" MODIFY ("TEXTID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEXTS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEXTS" MODIFY ("MODULECODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEXTS" MODIFY ("MODULE_MODULECODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEXTS" MODIFY ("MODULE_COURSECODE1" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEXTS" MODIFY ("MODULE_DEPTID1" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEXTS" ADD CONSTRAINT "TEXTS_PK" PRIMARY KEY ("TEXTID", "MODULE_MODULECODE", "MODULE_COURSECODE1", "MODULE_DEPTID1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
